from tkinter import *
from tkinter import ttk
root = Tk()
root.title('Phone List')
root.geometry("450x300")
l1=Label(root,text = "Name: ").place(x=50,y=10)
t=Entry(root,width=35).place(x=130,y=10)
l2=Label(root,text="Phone ").place(x=50,y=40)
t=Entry(root,width=35).place(x=130,y=40)
button=Button(root, text='Add', width=8).place(x=40,y=70)
button=Button(root, text='Update', width=10).place(x=130,y=70)
button=Button(root, text='Delete', width=10).place(x=230,y=70)
style = ttk.Style()
style.theme_use("default")
frame = Frame(root,width=10,height=100)
frame.pack()
frame.place(x=20,y=110)
tv = ttk.Treeview(frame, columns=(1, 2,3), show='headings', height=7)
tv.pack(side=LEFT)
tv.heading(1, text="Name",anchor="w")
tv.heading(2, text="Phone",anchor="w")
tv.heading(3, text="    ",anchor="w")
tv.column("# 1",width=150)
tv.column("# 2",width=110)
tv.column("# 3",width=50)
def update_item():
    selected = tv.focus()
tv.insert('', index=0,values=("Barnhart, Ralph","683-2341"))
tv.insert('', index=1,values=("Jones, Janet", "483-5432"))
tv.insert('', index=2,values=("Meyers, Chris", "343-4349"))
tv.insert('', index=3,values=("Nelson, Eric", "485-2689"))
tv.insert('', index=4,values=("Prefect, Ford","987-6543"))
tv.insert('', index=5,values=("Smith, Bob","689-1234"))
tv.insert('', index=6,values=("Smith, Robert","689-1235"))
tv.insert('', index=7,values=("Shanti, Jayanth","632-1357"))

sb = Scrollbar(frame, orient=VERTICAL)
sb.pack(side=RIGHT, fill=Y)

tv.config(yscrollcommand=sb.set)
sb.config(command=tv.yview)
root.mainloop()